### ISSUE TITLE
Unable to connect to server: libnetconf ERROR: Input channel error

### ISSUE THREAD

**Issue by gupta-neha** [CESNET/netopeer#58]
I am trying to connect to netopeer server from the client. But, I am getting an error: Input Chanel error

/usr/local/bin$ ./netopeer-server 
/usr/local/bin$ ./netopeer-cli 
/.netconf_client/config.xml:1: parser error : Document is empty

^
/.netconf_client/config.xml:1: parser error : Start tag expected, '<' not found

^
load_config: Failed to load configuration of NETCONF client (xmlReadFile failed).
netconf> connect --port 830 --login username localhost
username@localhost password: 
libnetconf ERROR: Input channel error
connect: connecting to the localhost failed.

I am not able to connect to server. I have already added the port and subsystem information in sshd config file.
Can you please tell me what I am doing wrong.

**Comment by michalvasko** [comment]
Hi,

for one, delete the file *~/.netconf_client/config.xml* for CLI configuration to be stored. Now, where did you find information that you have to modify your SSHD file? That is not true for a long time, *netopeer-server* 0.7.x (which works with *libnetconf* 0.9.x) has its own SSHD config file and you do not need to modify manually anything. *netopeer-server* 0.8.0 (*libnetconf* 0.10.x, both are the newest) does not use SSHD at all. Try to set your SSHD configuration back, use the netopeer from the master branch if not already, and try it again.

Regards,
Michal

**Comment by gupta-neha** [comment]
Hi,

Thanks for the quick reply.
When I try to use the master branch of netopeer, I get the following error while ./configure

gcc -Wall -Wextra -O3 -pthread -DNP_SSH -I/usr/local/include    -DRCSID=\""released as version 0.8.0"\" -I/usr/include/libxml2 .obj/src/server.o .obj/src/cfgnetopeer_transapi.o .obj/src/netconf_server_transapi.o .obj/src/ssh/server_ssh.o .obj/src/ssh/cfgnetopeer_transapi_ssh.o .obj/src/ssh/netconf_server_transapi_ssh.o -lcrypt -lssh -lnetconf -L/usr/local/lib -lnetconf    -lxml2 -o netopeer-server;
.obj/src/cfgnetopeer_transapi.o: In function `callback_n_netopeer_n_hello_timeout':
cfgnetopeer_transapi.c:(.text+0x46c): undefined reference to `nc_hello_timeout'
cfgnetopeer_transapi.c:(.text+0x4fa): undefined reference to `nc_hello_timeout'

**Comment by michalvasko** [comment]
Hi,

this is caused by failing to link with the correct *libnetconf*. Remove older versions and be sure to link *netopeer* with the newest version. After cleaning up call *# ldconfig* and then you can check which *libnetconf* is in its cache using *# ldconfig -p*.

Regards,
Michal

**Comment by gupta-neha** [comment]
Hi,

Thanks a lot. I was finally able to compile both server and client. However, when I tried connecting client to the server, I got the following error:

Server side:
Downloads/netopeer-master/server$ sudo ./netopeer-server 
netopeer-server[20143]: np_ssh_create_client: SSH key exchange error (src/ssh/server_ssh.c:1017): Socket error: disconnected

Client side:
load_config: Failed to load configuration of NETCONF client (xmlReadFile failed).
netconf> 
netconf> connect --port 830 -login username localhost
libnetconf ERROR: Starting the SSH session failed (kex error : no match for method server host key algo: server [ssh-rsa], client [ecdsa-sha2-nistp256])
connect: connecting to the (null):830 as user "ogin" failed.
netconf>

**Comment by michalvasko** [comment]
Hi,

this issue already occurred to someone else (#53) and I did not know how to help. I will try to find out whether that user managed to resolve it on his own. Just for information, what Linux distribution are you using?

Regards,
Michal

**Comment by gupta-neha** [comment]
Hi,
I am using Ubuntu 14.04.3 LTS. Okay, thanks a lot. Let me know if you get any solution.

**Comment by michalvasko** [comment]
Hi,

yes, this might very well be the problem. What I don't understand is how you managed to install *netopeer* if configure returned this error. It should also have told you what was wrong, your *libssh* version is too old.

Regards,
Michal

**Comment by gupta-neha** [comment]
When I run ./configure, in the output I get this:

checking for nc_session_accept_libssh_channel in -lnetconf... yes
checking for library containing ssh_pki_key_ecdsa_name... -lssh
checking for library containing crypt... -lcrypt
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu

It is able to find a library containing ssh_pki_key_ecdsa_name. Also, I have libssh 0.6.4 installed which I think is sufficient.

But in the config.log file, it prints the error which I mentioned earlier. Is there any way to check which version of libssh is being linked with the server?

I am not sure how should I fix this. Can you please help me out.

**Comment by michalvasko** [comment]
Hi,

you should be able to see what libraries are linked with *netopeer-server* if you run the *ldd* utility on it. You can also try setting the *LD_PRELOAD* environment variable (either using *export* or it must be done in the same command as starting the server) to the path to libssh >= 0.6.4 shared object, that way you make sure it gets loaded. 

Regards,
Michal

**Comment by mohitccem** [comment]
try clearing the keys and start the server again , command -> .ssh/known_hosts
